stages:
  - build
  - lint_format
  - migrations
  - test
  - deploy

default:
  image: docker:24.0.7
  pull_policy: if-not-present # Не скачивать каждый раз, если образ уже есть

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .


Lint:
  stage: lint_format
  script:
    - docker run --rm --network bookingNetwork booking-api-image ruff check

Format:
  stage: lint_format
  script:
    - docker run --rm --network bookingNetwork booking-api-image ruff format


Migrations:
  stage: migrations
  script:
    - docker run --rm --network bookingNetwork booking-api-image alembic upgrade head


Tests:
  stage: test
  script:
    - docker run --rm --network bookingNetwork booking-api-image pytest -s


deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose.cicd.yml up -d
    - docker exec booking_nginx nginx -s reload
