services:
  migrations:
    image: booking-api-image:latest
    command: >
      sh -c "
        echo '🔄 Запуск миграций...' &&
        alembic upgrade head &&
        echo '✅ Миграции применены'
      "
    restart: "no"
    networks:
      - bookingNetwork

  booking_back_service:
    container_name: "booking_back"
    image: booking-api-image:latest
    networks:
      - bookingNetwork
    depends_on:
      migrations:
        condition: service_completed_successfully

  celery_worker_service:
    container_name: "booking_celery_worker"
    image: booking-api-image:latest
    networks:
      - bookingNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
    depends_on:
      migrations:
        condition: service_completed_successfully

  celery_beat_service:
    container_name: "booking_celery_beat"
    image: booking-api-image:latest
    networks:
      - bookingNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"
    depends_on:
      migrations:
        condition: service_completed_successfully

networks:
  bookingNetwork:
    external: True
