# Это расширенная настройка nginx, применяется для установки ограничения на количества подключений
# Монтируется в контейнер nginx     - ./hosts/full_back_nginx.conf:/etc/nginx/nginx.conf:ro

worker_processes auto;
pid /run/nginx.pid;


events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # 🔥 === RATE LIMITING: Зона ограничения ===
    # Объявление зоны (только в http {})
    limit_req_zone $binary_remote_addr zone=my_limit:10m rate=5r/s;
    limit_req_log_level warn;
    limit_req_status 429;

    # Зона для ограничения соединений
    limit_conn_zone $binary_remote_addr zone=my_conn_limit:10m;

    server {
        listen 80;
        server_name localhost, anikeev-maks.ru;

        location / {
            proxy_pass http://booking_back:8000;

            # Заголовки для бэкенда
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 🔥 === Применяем rate limit ===
            limit_req zone=my_limit;

            # Ограничение одновременных подключений
            limit_conn my_conn_limit 10;
            limit_conn_status 429;
        }

        # 🔍 Health check для оркестраторов (без лимита)
        location /nginx-health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}