# Это настройка nginx для прода с ssl сертификатами только для маршрутизации, меняет только опциональный файл nginx
# Монтируется в контейнер nginx     - ./hosts/back_nginx.conf:/etc/nginx/conf.d/default.conf

server {
    listen 80;
    server_name anikeev-maks.ru localhost;

    # 🔥 Автоматический редирект всех запросов на HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name anikeev-maks.ru localhost;

    location / {
        proxy_pass http://booking_back:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
        ssl_certificate /etc/letsencrypt/live/anikeev-maks.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/anikeev-maks.ru/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}